### ISSUE TITLE
Use Melodica for your own wedding a.k.a. eat your own doc food

### ISSUE THREAD

**Issue by dtddj** [valo/melodica-inventory#67]
In order to reveal missing features, let us use Meldocia to plan your own wedding.

# Status Quo

@galiakraicheva & @valo have already completed:

- [x] find partner for life
- [x] party hard before the wedding
- [x] invite family and friends
 
# Hints

- @valo 
> Can this wife stop pumping? The strongest partner in town 🎢
> **Source:** https://twitter.com/valentinmihov/status/1304164399905681408?s=20

- @galiakraicheva 
> Pick your partner as if your life depends on it because it actually does!
> **Source:** https://twitter.com/galiakraicheva/status/1278337709468254209?s=20

# ToDo

- [x] show up on wedding day
- [x] convince parents to free doughter
- [x] say yes in public
- [x] kiss your partner
- [x] party hard (again)

---

_All the best!_
_DJ_
